#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

name: Update docs

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Update docs
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: Install Sphinx
        run: pip install sphinx sphinx_rtd_theme

      - name: Build docs
        run: make -C docs html BUILDDIR=${{ github.workspace }}/build "SPHINXOPTS=-W -E"
